SET(currentFolder "src/java/uk/co/progger/alienFXLite")

SET(JAVA_ALIENFX_SRC
  ${currentFolder}/AlienFXProperties.java
  ${currentFolder}/JarClassLoader.java
  ${currentFolder}/Launcher.java
  ${currentFolder}/Main.java
  ${currentFolder}/alienfx/AlienFXAction.java
  ${currentFolder}/alienfx/AlienFXActionBlink.java
  ${currentFolder}/alienfx/AlienFXActionColor.java
  ${currentFolder}/alienfx/AlienFXActionMorph.java
  ${currentFolder}/alienfx/AlienFXEngine.java
  ${currentFolder}/alienfx/AlienFXProfile.java
  ${currentFolder}/alienfx/AlienFXProfiles.java
  ${currentFolder}/alienfx/AlienFXProfileSetting.java
  ${currentFolder}/gui/ActionClipboard.java
  ${currentFolder}/gui/ActionPanel.java
  ${currentFolder}/gui/ActionPanelFX.java
  ${currentFolder}/gui/AddActionPanel.java
  ${currentFolder}/gui/AlienFXAlreadyRunningException.java
  ${currentFolder}/gui/AlienFXLiteGUIConstants.java
  ${currentFolder}/gui/AlienFXResources.java
  ${currentFolder}/gui/AlienFXTexts.java
  ${currentFolder}/gui/ColorBasePanel.java
  ${currentFolder}/gui/ColorChooserPanel.java
  ${currentFolder}/gui/ColorModel.java
  ${currentFolder}/gui/ColorPanel.java
  ${currentFolder}/gui/ColorUsedPanel.java
  ${currentFolder}/gui/DashedBorder.java
  ${currentFolder}/gui/DeviceInfoPanel.java
  ${currentFolder}/gui/DropDownButton.java
  ${currentFolder}/gui/JXTrayIcon.java
  ${currentFolder}/gui/MainFrame.java
  ${currentFolder}/gui/ProfileModel.java
  ${currentFolder}/gui/ProfilePanel.java
  ${currentFolder}/gui/ProfileSelectionPanel.java
  ${currentFolder}/gui/RegionPanel.java
  ${currentFolder}/led/AlienFXAllPowerFull.java
  ${currentFolder}/led/AlienFXArea51Controller.java
  ${currentFolder}/led/AlienFXCommunicationException.java
  ${currentFolder}/led/AlienFXController.java
  ${currentFolder}/led/AlienFXControllerFactory.java
  ${currentFolder}/led/AlienFXControllerNotFoundException.java
  ${currentFolder}/led/AlienFXControllerUnknownDeviceException.java
  ${currentFolder}/led/AlienFXM14xR2Controller.java
  ${currentFolder}/led/AlienFXM14xR3Controller.java
  ${currentFolder}/led/AlienFXM17xController.java
  ${currentFolder}/led/AlienFXM18xR2Controller.java
  ${currentFolder}/led/AlienFXPowerMode.java
  ${currentFolder}/led/AlienFXRegion.java
  ${currentFolder}/led/LEDController.java
)
